version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${POSTGRES_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: metabase-postgres
    restart: always
    ports:  # Adicionado mapeamento de portas
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}     
      POSTGRES_DB: metabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
